- name: Include variables
  include_vars: juntar_reportes_vars.yml
  no_log: true

- name: Juntar Reportes de "{{ nombre_reporte }}"
  become: True
  raw: "{{ script_name }} -n {{ nombre_consulta }} -t {{ tipo_consulta }} 2>&1 > /dev/null"