- name: Include variables
  include_vars: juntar_reportes_vars.yml
  no_log: true

- name: Juntar Reportes de "{{ nombre_reporte }}"
  become: True
  become_user: userapp
  shell: "{{ script_name }} -n {{ nombre_reporte }}"
  args:
    executable: /bin/bash