- name: Include variables
  include_vars: consultar_estatus_vars.yml
  no_log: true

- name: Consultar Estatus de "{{ nombre_consulta }}"
  become: True
  raw: "{{ script_name }} -n {{ nombre_consulta }}"
  register: salida_tail

- name: Mostrar el estatus de "{{ nombre_consulta }}"
  debug:
    var: salida_tail
    verbosity: 2