- name: Include variables
  include_vars: consultar_estatus_vars.yml
  no_log: true

- name: Consultar Estatus de "{{ nombre_consulta }}"
  become: True
  shell: "{{ script_name }} -n {{ nombre_consulta }}"
  args:
    executable: /bin/bash
  register: salida_tail

- name: Mostrar el estatus de "{{ nombre_consulta }}"
  debug:
    var: salida_tail.stdout_lines