- name: Include variables
  include_vars: gen_consultas_vars.yml
  no_log: true

- name: Generar Consultas "{{ nombre_consulta }}"
  become: True
  command: "{{ script_name }} -n {{ nombre_consulta }} -t {{ tipo_consulta }} 2>&1 > /dev/null"
  register: mi_salida