- name: Include variables
  include_vars: borrar_todos_vars.yml
  no_log: true

- name: Ejecutar Script "{{ script_name }}"
  become: True
  become_user: userapp
  shell: "{{ script_name }}"
  chdir: "{{ working_directory }}"
  args:
    executable: /bin/bash